//! # ralph-tui
//!
//! Terminal user interface for the Ralph Orchestrator framework.
//!
//! Built with `ratatui` and `crossterm`, this crate provides:
//! - Read-only observation dashboard for monitoring agent orchestration
//! - Real-time display of agent messages and state
//! - Keyboard navigation and search

mod animation;
mod app;
mod chat;
mod external_event_writer;
pub mod input;
pub mod state;
pub mod theme;
pub mod widgets;

use anyhow::Result;
use app::App;
use ralph_adapters::MarkdownRenderMode;
use ralph_core::HatJobOutputChunk;
use ralph_proto::{Event, HatId, HatInstanceId, HatInstanceState};
use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use tokio::sync::mpsc;
use tokio::sync::watch;

pub use app::dispatch_action;
pub use state::TuiState;
pub use state::{TuiMode, TuiUpdate};
pub use widgets::{footer, header};

/// Main TUI handle that integrates with the event bus.
pub struct Tui {
    state: Arc<Mutex<TuiState>>,
    terminated_rx: Option<watch::Receiver<bool>>,
    /// Channel to signal main loop on Ctrl+C.
    /// In raw terminal mode, SIGINT is not generated by the OS, so TUI must
    /// detect Ctrl+C via crossterm events and signal the main loop directly.
    interrupt_tx: Option<watch::Sender<bool>>,

    /// 并行模式：observer → channel → reducer 的更新通道（由 App 消费）。
    update_rx: Option<mpsc::UnboundedReceiver<TuiUpdate>>,
    update_tx: Option<mpsc::UnboundedSender<TuiUpdate>>,
}

impl Tui {
    /// Creates a new TUI instance with shared state.
    pub fn new() -> Self {
        Self {
            state: Arc::new(Mutex::new(TuiState::new())),
            terminated_rx: None,
            interrupt_tx: None,
            update_rx: None,
            update_tx: None,
        }
    }

    /// 创建并行模式的 Supervisor TUI（instance/job 维度）。
    pub fn new_parallel() -> Self {
        let (tx, rx) = mpsc::unbounded_channel();
        Self {
            state: Arc::new(Mutex::new(TuiState::new_parallel())),
            terminated_rx: None,
            interrupt_tx: None,
            update_rx: Some(rx),
            update_tx: Some(tx),
        }
    }

    /// 设置并行输出的 Markdown 渲染模式。
    ///
    /// 说明：
    /// - 该接口由 `ralph-cli` 侧调用，用于让 `--plain` 之类的开关能“向下传递”到 TUI。
    /// - 并行 Supervisor TUI 的输出视图会按该模式渲染：
    ///   - stdout：Rendered 会 best-effort 渲染 Markdown；Plain 保留 Markdown 控制符原样可见（同时保留 ANSI 解析）
    ///   - stderr：与 stdout 保持一致的渲染模式，但会弱化颜色避免抢眼
    #[must_use]
    pub fn with_parallel_output_render_mode(self, render_mode: MarkdownRenderMode) -> Self {
        // 这里的职责很简单：把渲染模式写入 state，让并行输出视图能按模式渲染。
        //
        // 说明：
        // - 默认是 Rendered（更易读）。
        // - CLI 传入 `--plain` 时会设置为 Plain（方便排障/复制粘贴/对齐旧行为）。
        if let Ok(mut state) = self.state.lock() {
            state.parallel.output_render_mode = render_mode;
        }
        self
    }

    /// 设置并行 Supervisor TUI：每个 job 的输出缓冲上限（按“逻辑行”计数）。
    ///
    /// 说明：
    /// - 该值只影响 TUI 的回看/搜索窗口，不影响 `.ralph/events*.jsonl` 或 `--record-session` 的落盘内容。
    /// - 设为 0 表示不保留输出（极端省内存/降噪场景）。
    #[must_use]
    pub fn with_parallel_max_buffer_lines(self, max_buffer_lines: usize) -> Self {
        if let Ok(mut state) = self.state.lock() {
            state.parallel.max_buffer_lines = max_buffer_lines;
        }
        self
    }

    /// 旧接口/兼容接口：是否在并行 TUI 中启用 Markdown 渲染。
    ///
    /// 说明：
    /// - `ralph-cli` 侧目前用一个 bool（`!plain`）表达渲染开关。
    /// - 该接口等价于 `with_parallel_output_render_mode(...)` 的语义糖。
    #[must_use]
    pub fn with_parallel_markdown_rendering(self, enabled: bool) -> Self {
        let render_mode = if enabled {
            MarkdownRenderMode::Rendered
        } else {
            MarkdownRenderMode::Plain
        };
        self.with_parallel_output_render_mode(render_mode)
    }

    /// Sets the hat map for dynamic topic-to-hat resolution.
    ///
    /// This allows the TUI to display the correct hat for custom topics
    /// without hardcoding them in TuiState::update().
    #[must_use]
    pub fn with_hat_map(self, hat_map: HashMap<String, (HatId, String)>) -> Self {
        if let Ok(mut state) = self.state.lock() {
            *state = TuiState::with_hat_map(hat_map);
        }
        self
    }

    /// 注入 hats graph radar 的“文字图”渲染结果（用于右上角拓扑小地图）。
    ///
    /// 说明：
    /// - 文字图由 `ralph-cli` 在启动 TUI 时生成（从 config + registry），TUI 只负责展示；
    /// - 默认使用 Unicode box-drawing 字符（┌─┐│└┘▶），对齐 `beautiful-mermaid-rs --ascii` 的输出；
    /// - `ascii_compact` 用于小窗视图（更紧凑），`ascii_full` 用于放大视图（更可读）。
    #[must_use]
    pub fn with_hat_graph_radar(self, ascii_compact: String, ascii_full: String) -> Self {
        if let Ok(mut state) = self.state.lock() {
            state.set_hat_graph_radar(ascii_compact, ascii_full);
        }
        self
    }

    /// Sets the termination signal receiver for graceful shutdown.
    ///
    /// The TUI will exit when this receiver signals `true`.
    #[must_use]
    pub fn with_termination_signal(mut self, terminated_rx: watch::Receiver<bool>) -> Self {
        self.terminated_rx = Some(terminated_rx);
        self
    }

    /// Sets the interrupt channel for Ctrl+C signaling.
    ///
    /// In raw terminal mode, SIGINT is not generated by the OS when the user
    /// presses Ctrl+C. The TUI detects Ctrl+C via crossterm events and uses
    /// this channel to signal the main orchestration loop to terminate.
    #[must_use]
    pub fn with_interrupt_tx(mut self, interrupt_tx: watch::Sender<bool>) -> Self {
        self.interrupt_tx = Some(interrupt_tx);
        self
    }

    /// Returns the shared state for external updates.
    pub fn state(&self) -> Arc<Mutex<TuiState>> {
        Arc::clone(&self.state)
    }

    /// 返回并行模式的 update sender（用于 CLI/Supervisor observers 推送更新）。
    pub fn update_sender(&self) -> Option<mpsc::UnboundedSender<TuiUpdate>> {
        self.update_tx.clone()
    }

    /// Returns an observer closure that updates TUI state from events.
    pub fn observer(&self) -> impl Fn(&Event) + Send + 'static {
        let state = Arc::clone(&self.state);
        move |event: &Event| {
            if let Ok(mut s) = state.lock() {
                s.update(event);
            }
        }
    }

    /// 并行：输出观察者（按实例归因的 stdout/stderr 行）。
    pub fn parallel_output_observer(&self) -> impl Fn(&HatJobOutputChunk) + Send + Sync + 'static {
        let tx = self
            .update_tx
            .clone()
            .expect("parallel_output_observer requires Tui::new_parallel()");
        move |chunk: &HatJobOutputChunk| {
            let _ = tx.send(TuiUpdate::ParallelOutputChunk(chunk.clone()));
        }
    }

    /// 并行：实例状态观察者（Running/Idle/Done/...）。
    pub fn parallel_instance_state_observer(
        &self,
    ) -> impl Fn(&HatInstanceId, HatInstanceState) + Send + Sync + 'static {
        let tx = self
            .update_tx
            .clone()
            .expect("parallel_instance_state_observer requires Tui::new_parallel()");
        move |instance_id: &HatInstanceId, state: HatInstanceState| {
            let _ = tx.send(TuiUpdate::ParallelInstanceState {
                instance_id: instance_id.clone(),
                state,
            });
        }
    }

    /// 并行：事件观察者（gate.* / human.message 等）。
    pub fn parallel_event_observer(&self) -> impl Fn(&Event) + Send + Sync + 'static {
        let tx = self
            .update_tx
            .clone()
            .expect("parallel_event_observer requires Tui::new_parallel()");
        move |event: &Event| {
            let _ = tx.send(TuiUpdate::ParallelEvent(event.clone()));
        }
    }

    /// Runs the TUI application loop.
    ///
    /// # Panics
    ///
    /// Panics if `with_termination_signal()` was not called before running.
    ///
    /// # Errors
    ///
    /// Returns an error if the terminal cannot be initialized or
    /// if the application loop encounters an unrecoverable error.
    pub async fn run(self) -> Result<()> {
        let terminated_rx = self
            .terminated_rx
            .expect("Termination signal not set - call with_termination_signal() first");
        let app = App::new(
            Arc::clone(&self.state),
            terminated_rx,
            self.interrupt_tx,
            self.update_rx,
        );
        app.run().await
    }
}

impl Default for Tui {
    fn default() -> Self {
        Self::new()
    }
}
